### ISSUE TITLE
DEMO doesn't work

### ISSUE THREAD

**Issue by juandc** [mjanssen/aural#1]
There is an error every time I test a button in the [demo](https://stackblitz.com/edit/aural): `Cannot read property 'play|pause|stop' of null`.

I think the problem is the [mp3 url](https://codepen.devnation.net/audio/sample.mp3) that is wrong :thinking:.

**Comment by mjanssen** [comment]
Thanks for the heads up! I looks like the asset server has some issues right now. Looking into the issue!

**Comment by juandc** [comment]
Cool. Probably the library must have an `error-controller` or something like that for preventing applications go down :+1:.

**Comment by mjanssen** [comment]
All right, server settings are restored and the demo page is working again 😁 
I'll have to look into error handling soon 👌

**Comment by mjanssen** [comment]
I still notice there's no audio playing when you initially open the page, but starts playing when you refresh the Stackblitz window 🤔. Re-opening to look into this issue.

**Comment by mjanssen** [comment]
All right, the library is updated to take the new 'mute-audio' feature for upcoming browsers in account. Audiocontext will automatically be resumed whenever you start or play an audio file, if the context has not already be resumed.

For the demo, an event triggered by the user is required to resume the Audiocontext 😁
